version: "3.9"
services:
  db-test:
    container_name: db-test
    image: postgres:15.1-alpine
    ports:
      - "2345:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=menutest

  elasticsearch-test:
    image: elasticsearch:7.14.2
    container_name: elasticsearch-test
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  app-test:
    build: .
    container_name: app-test
    command: bash -c "pytest tests.py"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL_P=postgresql+asyncpg://postgres:mypassword@db-test/menutest
      - NAME=elasticsearch-test
    depends_on:
      db-test:
        condition: service_healthy
      elasticsearch-test:
        condition: service_healthy

